version: '3'
services:
        db:
                image: mysql:8.0.22
                container_name: mysql_db
                ports:
                        - "3307:3306"
                environment:
                        MYSQL_ROOT_PASSWORD: "Tmddms0722@"
                command:
                        - --character-set-server=utf8mb4
                        - --collation-server=utf8mb4_unicode_ci
                volumes:
                         - ./db:/var/lib/mysql  
                restart: always
